spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: developer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

  packagesToScan: com.helpdesk.api.controller
